// <auto-generated />
namespace DatabaseFirstDemo.ReverseEngineeredCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-beta1-30515")]
    public sealed partial class van_TPH_naar_TPT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(van_TPH_naar_TPT));
        
        string IMigrationMetadata.Id
        {
            get { return "201406201331504_van_TPH_naar_TPT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
