//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor : Person
    {
        public Instructor()
        {
            this.Course = new HashSet<Course>();
        }
    
        public System.DateTime HireDate { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<Course> Course { get; set; }
    }
}
